export const FETCHING_CARS = 'FETCHING_CARS';
export const FETCHING_CARS_SUCCESS = 'FETCHING_CARS_SUCCESS';
export const FETCHING_CARS_FAILED = 'FETCHING_CARS_FAILED';

export const FETCHING_CAR = 'FETCHING_CAR';
export const FETCHING_CAR_SUCCESS = 'FETCHING_CAR_SUCCESS';
export const FETCHING_CAR_FAILED = 'FETCHING_CAR_FAILED';